name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://github.com/${GITHUB_REPOSITORY}
          cd ${GITHUB_REPOSITORY##*/}
          git checkout gh-pages
          cp -r ../build/* .
          git add .
          git commit -m "Deploy React app"
          git push -f origin gh-pages
